# Generated by Django 5.2.9 on 2025-12-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMovieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdbId', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.CharField(blank=True, max_length=20)),
                ('poster_path', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'raw_movie_data',
            },
        ),
    ]
